In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/Sample - Superstore.csv', encoding='latin 1')
print("Shape:", df.shape)
df.head()

Shape: (9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Duplicate rows: 0

In [5]:
df = df.drop_duplicates()
print(df.shape)

(9994, 21)

In [6]:
df['Order Date'] =  pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

print(df['Order Date'].dtype)
print(df['Ship Date'].dtype)

datetime64[ns]
datetime64[ns]

In [12]:
df['Order Year']    = df['Order Date'].dt.year
df['Order Month']   = df['Order Date'].dt.month
df['Order Day']     = df['Order Date'].dt.day_name()
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days

print("New columns added!")
df[['Order Date', 'Order Year', 'Order Month', 'Shipping Days']].head()

New columns added!

  Order Date  Order Year  Order Month  Shipping Days
0 2016-11-08        2016           11              3
1 2016-11-08        2016           11              3
2 2016-06-12        2016            6              4
3 2015-10-11        2015           10              7
4 2015-10-11        2015           10              7

In [12]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'order Date', 'Order Year', 'Order Month', 'Order Day', 'Shipping Days']

In [13]:
df.columns = df.columns.str.strip().str.replace(' ', '_').str.lower()
print("Cleaned column names:")
print(df.columns.tolist())

Cleaned column names:
['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub-category', 'product_name', 'sales', 'quantity', 'discount', 'profit', 'order_year', 'order_month', 'order_day', 'shipping_date', 'shipping_days']

In [14]:
print("Negative Sales:", (df['sales'] < 0).sum())
print("Negative Profit:", (df['profit'] < 0).sum())

Negative Sales: 0
Negative Profit: 1871

In [15]:
print("Final shape:", df.shape)
print("\nData types:")
print(df.dtypes)
print("\nMissing values remaining:")
print(df.isnull().sum()[df.isnull().sum() > 0])

Final shape: (9994, 26)

Data types:
row_id                    int64
order_id                 object
order_date       datetime64[ns]
ship_date        datetime64[ns]
ship_mode                object
customer_id              object
customer_name            object
segment                  object
country                  object
city                     object
state                    object
postal_code               int64
region                   object
product_id               object
category                 object
sub-category             object
product_name             object
sales                   float64
quantity                  int64
discount                float64
profit                  float64
order_year                int32
order_month               int32
order_day                object
shipping_date             int64
shipping_days             int64
dtype: object

Missing values remaining:
Series([], dtype: int64)

In [16]:
df.to_csv('../data/superstore_clean.csv', index=False)
print("Clean dataset saved!")

Clean dataset saved!